import Link from "next/link";

export const metadata = {
  title: "Terms of Service — Daxerly",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-gray-950 text-gray-100">
      <div className="max-w-3xl mx-auto px-8 py-16 font-mono text-sm leading-relaxed">
        <Link
          href="/"
          className="text-[10px] tracking-[0.3em] text-zinc-600 uppercase hover:text-zinc-400 transition-colors"
        >
          &larr; Back to Daxerly
        </Link>

        <h1 className="text-2xl font-bold mt-8 mb-2 tracking-tight text-gray-100">
          Terms of Service
        </h1>
        <p className="text-zinc-500 text-xs mb-12">
          Last updated: July 1, 2026
        </p>

        <section className="space-y-8 text-zinc-400">
          <div>
            <h2 className="text-gray-100 font-semibold mb-2">1. Agreement to Terms</h2>
            <p>
              By accessing or using Daxerly (&quot;the Service&quot;), operated by Apoorv Darshan,
              you agree to be bound by these Terms of Service. If you do not agree to these
              terms, do not use the Service.
            </p>
          </div>

          <div>
            <h2 className="text-gray-100 font-semibold mb-2">2. Description of Service</h2>
            <p>
              Daxerly is a platform that connects to your productivity tools (GitHub and
              Google Calendar) and generates daily work receipts summarizing your activity
              with an estimated dollar value.
            </p>
          </div>

          <div>
            <h2 className="text-gray-100 font-semibold mb-2">3. Free Service</h2>
            <p>
              The Service is provided free of charge. There are no subscription fees or
              payments required to use Daxerly. We do not process payments or collect any
              payment information.
            </p>
          </div>

          <div>
            <h2 className="text-gray-100 font-semibold mb-2">4. Account Responsibilities</h2>
            <ul className="list-disc list-inside space-y-1 ml-2">
              <li>You must provide accurate information when creating your account.</li>
              <li>You are responsible for maintaining the security of your account.</li>
              <li>You must not share your account with others.</li>
              <li>You must be at least 13 years of age to use the Service.</li>
            </ul>
          </div>

          <div>
            <h2 className="text-gray-100 font-semibold mb-2">5. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc list-inside space-y-1 ml-2">
              <li>Use the Service for any unlawful purpose.</li>
              <li>Attempt to reverse engineer, decompile, or disassemble the Service.</li>
              <li>Interfere with or disrupt the Service or its infrastructure.</li>
              <li>Access the Service through automated means (bots, scrapers) without permission.</li>
              <li>Resell or redistribute the Service without authorization.</li>
            </ul>
          </div>

          <div>
            <h2 className="text-gray-100 font-semibold mb-2">6. Third-Party Integrations</h2>
            <p>
              The Service connects to third-party platforms. Your use of those platforms is
              governed by their respective terms of service. We are not responsible for the
              availability, accuracy, or content of third-party services.
            </p>
          </div>

          <div>
            <h2 className="text-gray-100 font-semibold mb-2">7. Intellectual Property</h2>
            <p>
              All content, branding, and code comprising the Service are the property of Apoorv
              Darshan. Your activity data remains yours. The receipts generated by the Service
              are provided for your personal use.
            </p>
          </div>

          <div>
            <h2 className="text-gray-100 font-semibold mb-2">8. Disclaimer of Warranties</h2>
            <p>
              The Service is provided &quot;as is&quot; and &quot;as available&quot; without warranties of any
              kind, either express or implied. We do not guarantee that the Service will be
              uninterrupted, error-free, or that activity valuations are accurate.
            </p>
          </div>

          <div>
            <h2 className="text-gray-100 font-semibold mb-2">9. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, Apoorv Darshan shall not be liable for
              any indirect, incidental, special, consequential, or punitive damages arising
              from your use of the Service, including but not limited to loss of data or
              profits.
            </p>
          </div>

          <div>
            <h2 className="text-gray-100 font-semibold mb-2">10. Termination</h2>
            <p>
              We reserve the right to suspend or terminate your account at any time for
              violation of these terms. You may terminate your account at any time by
              contacting us.
            </p>
          </div>

          <div>
            <h2 className="text-gray-100 font-semibold mb-2">11. Changes to Terms</h2>
            <p>
              We may update these Terms of Service from time to time. Continued use of the
              Service after changes constitutes acceptance of the new terms.
            </p>
          </div>

          <div>
            <h2 className="text-gray-100 font-semibold mb-2">12. Contact</h2>
            <p>
              For questions about these Terms of Service, contact us at{" "}
              <a
                href="mailto:ad13dtu@gmail.com"
                className="text-zinc-300 underline hover:text-white transition-colors"
              >
                ad13dtu@gmail.com
              </a>
              .
            </p>
          </div>
        </section>
      </div>
    </div>
  );
}
